src/CmsWebApi/Controllers/PagesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CmsWebApi.Models;
using System.Net.Http;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;
using System.Net;

namespace CmsWebApi.Controllers
{
    public class PagesController : Controller
    {
        private readonly string _url = "http://localhost:5000/api/pages";
        private readonly HttpClient _httpClient;

        public PagesController()
        {
            _httpClient = new HttpClient();
        }

        public async Task<IActionResult> Index(string searchString = "")
        {
            var result = await _httpClient.GetAsync(_url+ $"/?title={searchString}&count=0");
            var pages = await result.Content.ReadAsStringAsync();
            return View(JsonConvert.DeserializeObject<IEnumerable<Page>>(pages));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var result = await _httpClient.GetAsync(_url + $"/{id}");
            var page = JsonConvert.DeserializeObject<Page>(await result.Content.ReadAsStringAsync());
            if (page == null)
            {
                return NotFound();
            }
            return View(page);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Content,Description,Title,UrlName")] Page page)
        {
            if (ModelState.IsValid)
            {
                _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpContent content = new StringContent(JsonConvert.SerializeObject(page), Encoding.UTF8, "application/json");
                var response = await _httpClient.PostAsync(_url,content);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(page);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var result = await _httpClient.GetAsync(_url + $"/{id}");
            var page = JsonConvert.DeserializeObject<Page>(await result.Content.ReadAsStringAsync());
            if (page == null)
            {
                return NotFound();
            }
            return View(page);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AddedDate,Content,Description,Title,UrlName")] Page page)
        {
            if (id != page.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpContent content = new StringContent(JsonConvert.SerializeObject(page), Encoding.UTF8, "application/json");
                var response = await _httpClient.PutAsync(_url + $"/{id}", content);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else if (response.StatusCode == HttpStatusCode.NotFound)
                {
                    return NotFound();
                }
                else
                {
                    // pass exception to ui
                } 
                return RedirectToAction("Index");
            }
            return View(page);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var result = await _httpClient.GetAsync(_url + $"/{id}");
            var page = JsonConvert.DeserializeObject<Page>(await result.Content.ReadAsStringAsync());
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var response = await _httpClient.DeleteAsync(_url + $"/{id}");

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else if (response.StatusCode == HttpStatusCode.NotFound)
            {
                return NotFound();
            }
            else
            {
                // pass exception to ui
            }
            return RedirectToAction("Index");
        }

        [AcceptVerbs("Get", "Post")]
        public async Task<IActionResult> VerifyUrlName(string urlName, int id)
        {
            var result = await _httpClient.GetAsync(_url);
            var json = await result.Content.ReadAsStringAsync();
            var pages = JsonConvert.DeserializeObject<IEnumerable<Page>>(json);
            var urls = pages.Where(x => x.Id != id).Select(x => x.UrlName);
            if (urls.Contains(urlName))
            {
                return Json(data: $"URL name {urlName} is already in use. Think of a differenet one.");
            }

            return Json(data: true);
        }
    }
}

src/CmsWebApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CMS</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/tablesorter/themes/blue/style.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/tablesorter/themes/blue/style.min.css"/>
    </environment>
   
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/tablesorter/themes/blue/style.min.css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Pages" asp-action="Index" class="navbar-brand">Pages</a>
            </div>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - CmsMvc</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/tinymce/tinymce.js"></script>
        <script src="~/lib/tinymce/themes/modern/theme.js"></script>
        <script src="~/lib/tinymce/plugins/noneditable/plugin.min.js"></script>
        <script src="~/lib/tablesorter/jquery.tablesorter.js"></script>
        <script src="~/lib/tablesorter/jquery-latest.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/tinymce/tinymce.min.js"></script>
        <script src="~/lib/tinymce/jquery.tinymce.min.js"></script>
        <script src="~/lib/tinymce/themes/modern/theme.min.js"></script>
        <script src="~/lib/tinymce/plugins/noneditable/plugin.min.js"></script>
        <script src="~/lib/tablesorter/jquery.tablesorter.min.js"></script>
        <script src="~/lib/tablesorter/jquery-latest.min.js"></script>
    </environment>
    @RenderSection("scripts", required: false)
</body>
</html>